alias ls='ls -F -a --color=auto'
alias ll='ls -l'
alias sf='sudo nixos-rebuild switch --flake'
alias bf='sudo nixos-rebuild boot --flake'
alias cdf='cd $(find /etc/ /home/ -type d -name "flake-config" 2>/dev/null)'

cateval() {
   eval "$(cat $1)"
}

PS1="\[\e[32m\]\u\[\e[31m\]@\[\e[32m\]\h \[\e[31m\]:: \[\e[36m\]\w\n\[\e[33m\]%\[\e[0m\] "
